# -*- coding: utf-8 -*-
"""สำเนาของ plant_classification_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GbYLZZkXEEAa5KhH6zmlVZ9AwhXmhaa

# 🌿 Plant Part & Species Classification
### Hierarchical Classification: Plant Part → Species
**Model:** MobileNetV2 (Transfer Learning)

**Pipeline:**
1. ขั้นตอนที่ 1: ทำนายส่วนของพืช (`bark`, `flower`, `fruit`, `leaf`)
2. ขั้นตอนที่ 2: ทำนายชนิดของพืช (3 สายพันธุ์)

**โครงสร้างข้อมูล (Google Drive):**
```
planttest/
├── bark/
│   ├── species_1/ (100 images)
│   ├── species_2/ (100 images)
│   └── species_3/ (100 images)
├── flower/
├── fruit/
└── leaf/
```

## 📦 Step 1: Install & Import Libraries
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import json
from pathlib import Path

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.applications import MobileNetV3Large
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.utils import plot_model

from sklearn.metrics import classification_report, confusion_matrix
from PIL import Image

print(f'TensorFlow version: {tf.__version__}')
print(f'GPU available: {len(tf.config.list_physical_devices("GPU")) > 0}')

"""## 📂 Step 2: Mount Google Drive & Set Paths"""

from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# ✏️ แก้ไข path ให้ตรงกับตำแหน่ง planttest ใน Google Drive
# ============================================================
BASE_DIR = '/content/drive/MyDrive/planttest'

PLANT_PARTS = ['bark', 'flower', 'fruit', 'leaf']

# ตรวจสอบโครงสร้างโฟลเดอร์
print('📁 Dataset Structure:')
species_names = None
for part in PLANT_PARTS:
    part_path = os.path.join(BASE_DIR, part)
    if os.path.exists(part_path):
        species = sorted(os.listdir(part_path))
        species = [s for s in species if os.path.isdir(os.path.join(part_path, s))]
        if species_names is None:
            species_names = species
        print(f'  📂 {part}/ → {species}')
        for sp in species:
            sp_path = os.path.join(part_path, sp)
            img_count = len([f for f in os.listdir(sp_path) if f.lower().endswith(('.jpg','.jpeg','.png','.jfif'))])
            print(f'       └── {sp}: {img_count} images')
    else:
        print(f'  ❌ {part}/ NOT FOUND')

print(f'\n✅ Species detected: {species_names}')

"""## ⚙️ Step 3: Configuration"""

# ============================================================
# CONFIG — แก้ไขได้ตามต้องการ
# ============================================================
IMG_SIZE      = (224, 224)   # MobileNetV2 input size
BATCH_SIZE    = 32
EPOCHS_STAGE1 = 30           # Train top layers only
EPOCHS_STAGE2 = 50           # Fine-tune with unfrozen layers
LEARNING_RATE = 1e-3
FINE_TUNE_LR  = 1e-5
VAL_SPLIT     = 0.2
TEST_SPLIT    = 0.1
SEED          = 42
SAVE_DIR      = '/content/drive/MyDrive/plant_models'

os.makedirs(SAVE_DIR, exist_ok=True)

NUM_PARTS   = len(PLANT_PARTS)          # 4
NUM_SPECIES = len(species_names)        # 3

print(f'Parts  : {NUM_PARTS}  → {PLANT_PARTS}')
print(f'Species: {NUM_SPECIES} → {species_names}')
print(f'Image size: {IMG_SIZE}, Batch: {BATCH_SIZE}')

"""## 🗂️ Step 4: Prepare Datasets
สร้าง flat dataset สำหรับ **Part Classifier** และ per-part datasets สำหรับ **Species Classifier**
"""

import shutil, random
from sklearn.model_selection import train_test_split

PREPARED_DIR = '/content/plant_data'

def collect_images(base_dir, parts, species_names):
    """Returns list of (image_path, part_label, species_label)"""
    data = []
    for part in parts:
        for species in species_names:
            folder = os.path.join(base_dir, part, species)
            if not os.path.exists(folder):
                print(f'⚠️  Missing: {folder}')
                continue
            imgs = [f for f in os.listdir(folder)
                    if f.lower().endswith(('.jpg','.jpeg','.png','.jfif'))]
            for img in imgs:
                data.append((os.path.join(folder, img), part, species))
    return data

def prepare_flat_dataset(data, out_dir, label_fn, split=(0.7, 0.2, 0.1)):
    """Copy images into train/val/test folders by label."""
    random.seed(SEED)
    random.shuffle(data)
    n = len(data)
    tr = int(n * split[0])
    vl = int(n * (split[0] + split[1]))
    splits = {'train': data[:tr], 'val': data[tr:vl], 'test': data[vl:]}

    for subset, items in splits.items():
        for src_path, part, species in items:
            label = label_fn(part, species)
            dst_dir = os.path.join(out_dir, subset, label)
            os.makedirs(dst_dir, exist_ok=True)
            fname = f'{part}_{species}_{os.path.basename(src_path)}'
            shutil.copy2(src_path, os.path.join(dst_dir, fname))
    print(f'✅ Dataset prepared at: {out_dir}')
    for subset in ['train','val','test']:
        labels = os.listdir(os.path.join(out_dir, subset))
        print(f'   {subset}: {len(splits[subset])} images, classes={labels}')

# Collect all images
all_data = collect_images(BASE_DIR, PLANT_PARTS, species_names)
print(f'\nTotal images found: {len(all_data)}')

# ── 1. Part Classifier dataset ──────────────────────────────
PART_DATA_DIR = os.path.join(PREPARED_DIR, 'part_classifier')
if not os.path.exists(PART_DATA_DIR):
    prepare_flat_dataset(all_data, PART_DATA_DIR, label_fn=lambda p, s: p)
else:
    print(f'Part dataset already exists at {PART_DATA_DIR}')

# ── 2. Species Classifier dataset (one per part) ─────────────
for part in PLANT_PARTS:
    part_data = [(path, p, sp) for path, p, sp in all_data if p == part]
    sp_dir = os.path.join(PREPARED_DIR, f'species_{part}')
    if not os.path.exists(sp_dir):
        prepare_flat_dataset(part_data, sp_dir, label_fn=lambda p, s: s)
    else:
        print(f'Species/{part} dataset already exists')

"""## 🔧 Step 5: Data Generators with Augmentation"""

def make_generators(data_dir, batch_size=BATCH_SIZE, img_size=IMG_SIZE):
    train_gen = ImageDataGenerator(
        preprocessing_function=tf.keras.applications.mobilenet_v3.preprocess_input,
        rotation_range=20,
        width_shift_range=0.15,
        height_shift_range=0.15,
        zoom_range=0.2,
        horizontal_flip=True,
        brightness_range=[0.8, 1.2],
        fill_mode='nearest'
    )
    val_test_gen = ImageDataGenerator(
        preprocessing_function=tf.keras.applications.mobilenet_v3.preprocess_input
    )

    train = train_gen.flow_from_directory(
        os.path.join(data_dir, 'train'),
        target_size=img_size, batch_size=batch_size,
        class_mode='categorical', seed=SEED
    )
    val = val_test_gen.flow_from_directory(
        os.path.join(data_dir, 'val'),
        target_size=img_size, batch_size=batch_size,
        class_mode='categorical', seed=SEED
    )
    test = val_test_gen.flow_from_directory(
        os.path.join(data_dir, 'test'),
        target_size=img_size, batch_size=batch_size,
        class_mode='categorical', seed=SEED, shuffle=False
    )
    return train, val, test

# Create part classifier generators
part_train, part_val, part_test = make_generators(PART_DATA_DIR)
print(f'Part classes: {part_train.class_indices}')

# Create species generators per part
species_gens = {}
for part in PLANT_PARTS:
    sp_dir = os.path.join(PREPARED_DIR, f'species_{part}')
    tr, vl, te = make_generators(sp_dir)
    species_gens[part] = {'train': tr, 'val': vl, 'test': te}
    print(f'Species/{part} classes: {tr.class_indices}')

"""## 🏗️ Step 6: Build MobileNetV2 Model"""

def build_mobilenet_model(num_classes, model_name='model'):
    """
    MobileNetV2 Transfer Learning Model
    Stage 1: Freeze base → train head only
    Stage 2: Unfreeze top layers → fine-tune
    """
    base = MobileNetV3Large(
    input_shape=(*IMG_SIZE, 3),
    include_top=False,
    weights='imagenet'
    )
    base.trainable = False  # Freeze for Stage 1

    inputs = tf.keras.Input(shape=(*IMG_SIZE, 3))
    x = base(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)
    x = layers.Dense(256, activation='relu', name='fc1')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation='softmax', name='predictions')(x)

    model = models.Model(inputs, outputs, name=model_name)
    return model, base

def get_callbacks(model_name, save_dir=SAVE_DIR):
    return [
        ModelCheckpoint(
            filepath=os.path.join(save_dir, f'{model_name}_best.keras'),
            monitor='val_accuracy', save_best_only=True, verbose=1
        ),
        EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=7, min_lr=1e-7, verbose=1)
    ]

def train_two_stage(model, base_model, train_gen, val_gen, model_name,
                    epochs1=EPOCHS_STAGE1, epochs2=EPOCHS_STAGE2,
                    unfreeze_from=-20):
    """
    Two-stage training:
    Stage 1: Train head only (frozen base)
    Stage 2: Fine-tune top layers of base
    """
    # ── Stage 1 ──────────────────────────────
    print(f'\n🔵 Stage 1: Training head layers ({model_name})')
    model.compile(
        optimizer=optimizers.Adam(LEARNING_RATE),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    hist1 = model.fit(
        train_gen, validation_data=val_gen,
        epochs=epochs1,
        callbacks=get_callbacks(f'{model_name}_s1')
    )

    # ── Stage 2: Fine-tune ────────────────────
    print(f'\n🟠 Stage 2: Fine-tuning ({model_name})')
    base_model.trainable = True
    # Freeze all except last `|unfreeze_from|` layers
    for layer in base_model.layers[:unfreeze_from]:
        layer.trainable = False

    model.compile(
        optimizer=optimizers.Adam(FINE_TUNE_LR),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    hist2 = model.fit(
        train_gen, validation_data=val_gen,
        epochs=epochs2,
        callbacks=get_callbacks(f'{model_name}_s2')
    )

    # Save final model
    save_path = os.path.join(SAVE_DIR, f'{model_name}_final.keras')
    model.save(save_path)
    print(f'✅ Model saved: {save_path}')
    return hist1, hist2

print('Model builder ready ✅')

"""## 🌿 Step 7: Train Part Classifier (bark / flower / fruit / leaf)"""

part_model, part_base = build_mobilenet_model(NUM_PARTS, 'part_classifier')
part_model.summary()

part_hist1, part_hist2 = train_two_stage(
    part_model, part_base,
    part_train, part_val,
    model_name='part_classifier'
)

# Evaluate on test set
print('\n📊 Part Classifier — Test Evaluation:')
part_loss, part_acc = part_model.evaluate(part_test)
print(f'   Loss: {part_loss:.4f} | Accuracy: {part_acc:.4f}')

"""## 🌱 Step 8: Train Species Classifiers (one per part)"""

species_models = {}

for part in PLANT_PARTS:
    print(f'\n{'='*60}')
    print(f'  Training Species Classifier for: {part.upper()}')
    print(f'{'='*60}')

    model, base = build_mobilenet_model(NUM_SPECIES, f'species_{part}')

    h1, h2 = train_two_stage(
        model, base,
        species_gens[part]['train'],
        species_gens[part]['val'],
        model_name=f'species_{part}'
    )

    # Evaluate
    loss, acc = model.evaluate(species_gens[part]['test'])
    print(f'  [{part}] Test Accuracy: {acc:.4f}')

    species_models[part] = {
        'model': model,
        'class_indices': species_gens[part]['train'].class_indices,
        'hist': (h1, h2),
        'test_acc': acc
    }

print('\n✅ All species models trained!')

"""## 📊 Step 9: Plot Training History"""

def plot_history(hist1, hist2, title):
    fig, axes = plt.subplots(1, 2, figsize=(14, 4))
    fig.suptitle(title, fontsize=14, fontweight='bold')

    # Merge histories
    acc  = hist1.history['accuracy']  + hist2.history['accuracy']
    vacc = hist1.history['val_accuracy'] + hist2.history['val_accuracy']
    loss = hist1.history['loss'] + hist2.history['loss']
    vloss= hist1.history['val_loss'] + hist2.history['val_loss']
    stage2_start = len(hist1.history['accuracy'])

    for ax, metric, title_m in zip(axes, [(acc, vacc), (loss, vloss)], ['Accuracy', 'Loss']):
        m, vm = metric
        ax.plot(m,  label='Train', color='steelblue')
        ax.plot(vm, label='Val',   color='coral')
        ax.axvline(stage2_start, color='green', linestyle='--', alpha=0.7, label='Fine-tune start')
        ax.set_title(title_m); ax.set_xlabel('Epoch'); ax.legend(); ax.grid(alpha=0.3)

    plt.tight_layout()
    plt.show()

# Part classifier
plot_history(part_hist1, part_hist2, 'Part Classifier (bark/flower/fruit/leaf)')

# Species classifiers
for part in PLANT_PARTS:
    h1, h2 = species_models[part]['hist']
    plot_history(h1, h2, f'Species Classifier — {part.capitalize()}')

"""## 🔍 Step 10: Confusion Matrices & Classification Reports"""

def plot_confusion_matrix(model, test_gen, class_names, title):
    y_pred = np.argmax(model.predict(test_gen), axis=1)
    y_true = test_gen.classes

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title(f'Confusion Matrix: {title}')
    plt.ylabel('True Label'); plt.xlabel('Predicted Label')
    plt.tight_layout(); plt.show()

    print(classification_report(y_true, y_pred, target_names=class_names))

# Part classifier
part_classes = [k for k, v in sorted(part_train.class_indices.items(), key=lambda x: x[1])]
plot_confusion_matrix(part_model, part_test, part_classes, 'Part Classifier')

# Species classifiers
for part in PLANT_PARTS:
    sp_classes = [k for k, v in sorted(species_gens[part]['train'].class_indices.items(), key=lambda x: x[1])]
    plot_confusion_matrix(
        species_models[part]['model'],
        species_gens[part]['test'],
        sp_classes,
        f'Species/{part}'
    )

"""## 🔮 Step 11: Hierarchical Prediction Pipeline"""

# Load class index maps
part_idx2name = {v: k for k, v in part_train.class_indices.items()}
species_idx2name = {}
for part in PLANT_PARTS:
    species_idx2name[part] = {v: k for k, v in species_gens[part]['train'].class_indices.items()}

def preprocess_image(img_path):
    img = Image.open(img_path).convert('RGB').resize(IMG_SIZE)
    arr = np.array(img, dtype=np.float32)
    arr = tf.keras.applications.mobilenet_v3.preprocess_input(arr)
    return np.expand_dims(arr, axis=0)

def predict_plant(img_path, confidence_threshold=0.5, verbose=True):
    """
    Hierarchical prediction:
    1) Predict plant part (bark/flower/fruit/leaf)
    2) Predict species using the matching part model

    Returns: dict with part, species, confidence scores
    """
    img = preprocess_image(img_path)

    # ── Step 1: Part prediction ───────────────
    part_probs = part_model.predict(img, verbose=0)[0]
    part_idx   = np.argmax(part_probs)
    part_name  = part_idx2name[part_idx]
    part_conf  = float(part_probs[part_idx])

    # ── Step 2: Species prediction ────────────
    sp_probs  = species_models[part_name]['model'].predict(img, verbose=0)[0]
    sp_idx    = np.argmax(sp_probs)
    sp_name   = species_idx2name[part_name][sp_idx]
    sp_conf   = float(sp_probs[sp_idx])

    result = {
        'part':          part_name,
        'part_conf':     part_conf,
        'part_probs':    {part_idx2name[i]: float(p) for i, p in enumerate(part_probs)},
        'species':       sp_name,
        'species_conf':  sp_conf,
        'species_probs': {species_idx2name[part_name][i]: float(p) for i, p in enumerate(sp_probs)},
        'low_confidence': part_conf < confidence_threshold or sp_conf < confidence_threshold
    }

    if verbose:
        print(f'🌿 Part     : {part_name} ({part_conf*100:.1f}%)')
        print(f'🌱 Species  : {sp_name} ({sp_conf*100:.1f}%)')
        if result['low_confidence']:
            print('⚠️  Low confidence — result may be unreliable')

    return result

print('✅ Prediction pipeline ready!')

"""## 🖼️ Step 12: Test Prediction with Sample Images"""

def visualize_prediction(img_path):
    result = predict_plant(img_path, verbose=False)

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    # Original image
    img = Image.open(img_path).convert('RGB')
    axes[0].imshow(img)
    axes[0].set_title('Input Image', fontweight='bold')
    axes[0].axis('off')

    # Part probabilities
    parts   = list(result['part_probs'].keys())
    p_probs = list(result['part_probs'].values())
    colors  = ['steelblue' if p != result['part'] else 'coral' for p in parts]
    axes[1].barh(parts, p_probs, color=colors)
    axes[1].set_title(f'Part: {result["part"]} ({result["part_conf"]*100:.1f}%)', fontweight='bold')
    axes[1].set_xlim(0, 1)
    axes[1].axvline(0.5, color='gray', linestyle='--', alpha=0.5)

    # Species probabilities
    species  = list(result['species_probs'].keys())
    s_probs  = list(result['species_probs'].values())
    s_colors = ['steelblue' if s != result['species'] else 'green' for s in species]
    axes[2].barh(species, s_probs, color=s_colors)
    axes[2].set_title(f'Species: {result["species"]} ({result["species_conf"]*100:.1f}%)', fontweight='bold')
    axes[2].set_xlim(0, 1)
    axes[2].axvline(0.5, color='gray', linestyle='--', alpha=0.5)

    plt.suptitle(
        f'Prediction: {result["part"]} → {result["species"]}' +
        (' ⚠️ Low confidence' if result['low_confidence'] else ''),
        fontsize=13, fontweight='bold', color='red' if result['low_confidence'] else 'black'
    )
    plt.tight_layout()
    plt.show()
    return result

# Test on a few sample images from the test set
print('🔍 Testing on sample images...')
for part in PLANT_PARTS:
    test_dir = os.path.join(PREPARED_DIR, f'species_{part}', 'test')
    for sp in os.listdir(test_dir):
        sp_dir = os.path.join(test_dir, sp)
        imgs = [f for f in os.listdir(sp_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))]
        if imgs:
            sample = os.path.join(sp_dir, imgs[0])
            print(f'\n--- Sample: {part}/{sp} ---')
            visualize_prediction(sample)
            break
    break  # Show only first part for demo — remove to show all

"""## 💾 Step 13: Save Model Info & Class Mappings"""

# Save class mappings for deployment
class_info = {
    'part_classes': part_train.class_indices,
    'species_classes': {part: species_gens[part]['train'].class_indices for part in PLANT_PARTS},
    'img_size': list(IMG_SIZE),
    'parts': PLANT_PARTS
}

with open(os.path.join(SAVE_DIR, 'class_mappings.json'), 'w') as f:
    json.dump(class_info, f, indent=2)

print('✅ Saved class_mappings.json')

# Summary table
print('\n' + '='*55)
print('  FINAL RESULTS SUMMARY')
print('='*55)
loss, acc = part_model.evaluate(part_test, verbose=0)
print(f'  Part Classifier Test Accuracy : {acc*100:.2f}%')
for part in PLANT_PARTS:
    print(f'  Species/{part:<8} Test Accuracy : {species_models[part]["test_acc"]*100:.2f}%')
print('='*55)

import os

SAVE_DIR = "models"
os.makedirs(SAVE_DIR, exist_ok=True)

# 🔹 Save part model
part_model.save(os.path.join(SAVE_DIR, "part_model.keras"))

# 🔹 Save species models
for part in PLANT_PARTS:
    species_models[part]['model'].save(
        os.path.join(SAVE_DIR, f"species_{part}.keras")
    )

print("✅ Saved all models (.keras)")

import json
import os

SAVE_DIR = "models"
os.makedirs(SAVE_DIR, exist_ok=True)

def invert_dict(d):
    return {v: k for k, v in d.items()}

class_info = {
    'part_classes': invert_dict(part_train.class_indices),
    'species_classes': {
        part: invert_dict(species_gens[part]['train'].class_indices)
        for part in PLANT_PARTS
    },
    'img_size': list(IMG_SIZE),
    'parts': PLANT_PARTS
}

with open(os.path.join(SAVE_DIR, 'class_mappings.json'), 'w') as f:
    json.dump(class_info, f, indent=2)

print("✅ Saved class_mappings.json")

import os

print(os.listdir())

"""## 🖼️ Step 14: Predict Your Own Image"""

from google.colab import files

print('📤 Upload an image to predict:')
uploaded = files.upload()

for fname in uploaded.keys():
    print(f'\nPredicting: {fname}')
    result = visualize_prediction(fname)
    print(json.dumps(result, indent=2))

def show_misclassified(model, test_gen, idx2name, title, max_images=20):
    """
    แสดงรูปภาพที่โมเดลทำนายผิดพร้อม label จริง vs ที่ทำนาย
    """
    test_gen.reset()
    preds_prob = model.predict(test_gen, verbose=0)
    y_pred = np.argmax(preds_prob, axis=1)
    y_true = test_gen.classes
    filenames = test_gen.filenames

    wrong_idx = np.where(y_pred != y_true)[0]
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"  ทำนายผิด: {len(wrong_idx)} / {len(y_true)} รูป "
          f"({len(wrong_idx)/len(y_true)*100:.1f}%)")
    print(f"{'='*60}")

    if len(wrong_idx) == 0:
        print("  ✅ ไม่มีรูปที่ทำนายผิดเลย!")
        return

    show_idx = wrong_idx[:max_images]
    n = len(show_idx)
    cols = min(5, n)
    rows = (n + cols - 1) // cols

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3.5, rows * 3.8))
    axes = np.array(axes).reshape(-1) if n > 1 else [axes]

    data_dir = test_gen.directory

    for ax, idx in zip(axes, show_idx):
        img_path = os.path.join(data_dir, filenames[idx])
        img = Image.open(img_path).convert('RGB')

        true_label = idx2name[y_true[idx]]
        pred_label = idx2name[y_pred[idx]]
        conf       = preds_prob[idx][y_pred[idx]] * 100

        ax.imshow(img)
        ax.set_title(
            f"True : {true_label}\nPred : {pred_label} ({conf:.1f}%)",
            fontsize=9, color='red', fontweight='bold'
        )
        ax.axis('off')
        for spine in ax.spines.values():
            spine.set_edgecolor('red')
            spine.set_linewidth(2)
            spine.set_visible(True)

    for ax in axes[n:]:
        ax.axis('off')

    plt.suptitle(f"{title} — Misclassified ({n} images)", fontsize=12, fontweight='bold', color='red')
    plt.tight_layout()
    plt.show()


# ── Part Classifier ──────────────────────────────────────────
part_idx2name_local = {v: k for k, v in part_train.class_indices.items()}
show_misclassified(part_model, part_test, part_idx2name_local, "Part Classifier")

# ── Species Classifiers (แต่ละ part) ─────────────────────────
for part in PLANT_PARTS:
    sp_idx2name_local = {v: k for k, v in species_gens[part]['train'].class_indices.items()}
    show_misclassified(
        species_models[part]['model'],
        species_gens[part]['test'],
        sp_idx2name_local,
        f"Species Classifier — {part.capitalize()}"
    )

"""## 🔄 Step 15: Load Saved Models (Optional - For Later Use)"""

SAVE_DIR = '/content/drive/MyDrive/plant_models'

with open(os.path.join(SAVE_DIR, 'class_mappings.json'), 'r') as f:
    class_info = json.load(f)

part_model = tf.keras.models.load_model(os.path.join(SAVE_DIR, 'part_classifier_final.keras'))
species_models = {}
for part in PLANT_PARTS:
    model = tf.keras.models.load_model(os.path.join(SAVE_DIR, f'species_{part}_final.keras'))
    species_models[part] = {
        'model': model,
        'class_indices': class_info['species_classes'][part]
    }
part_idx2name = {v: k for k, v in class_info['part_classes'].items()}
species_idx2name = {part: {v: k for k,v in mp.items()} for part, mp in class_info['species_classes'].items()}
print('✅ All models loaded!')

import torch

# save weights
torch.save(model.state_dict(), "mobilenetv3.pth")

import torch
from torchvision import models

model = models.mobilenet_v3_large()
model.classifier[3] = torch.nn.Linear(1280, NUM_CLASSES)

model.load_state_dict(torch.load("mobilenetv3.pth", map_location="cpu"))
model.eval()